CC = gcc

all: cache1D cache1D4 cache1D32 cache1D64 cache2Drows cache2Dcols cache2Drows64 cache2Dcols64

cache1D: cache1D.c
	$(CC) -o cache1D cache1D.c -Wall -m32

cache2Drows: cache2Drows.c
	$(CC) -o cache2Drows cache2Drows.c -Wall -m32
	
cache2Dcols: cache2Dcols.c
	$(CC) -o cache2Dcols cache2Dcols.c -Wall -m32

cache1D4: cache1D
	/p/course/cs354-common/public/cache/pin -t /p/course/cs354-common/public/cache/source/tools/Memory/obj-ia32/allcache.so -is 16384 -ia 1 -ib 4 -ds 16384 -da 1 -db 4 -- cache1D

cache1D32: cache1D
	/p/course/cs354-common/public/cache/pin -t /p/course/cs354-common/public/cache/source/tools/Memory/obj-ia32/allcache.so -is 16384 -ia 1 -ib 32 -ds 16384 -da 1 -db 32 -- cache1D
	
cache1D64: cache1D
	/p/course/cs354-common/public/cache/pin -t /p/course/cs354-common/public/cache/source/tools/Memory/obj-ia32/allcache.so -is 16384 -ia 1 -ib 64 -ds 16384 -da 1 -db 64 -- cache1D

cache2Drows64: cache2Drows
	/p/course/cs354-common/public/cache/pin -t /p/course/cs354-common/public/cache/source/tools/Memory/obj-ia32/allcache.so -is 16384 -ia 1 -ib 64 -ds 16384 -da 1 -db 64 -- cache2Drows
	
cache2Dcols64: cache2Dcols
	/p/course/cs354-common/public/cache/pin -t /p/course/cs354-common/public/cache/source/tools/Memory/obj-ia32/allcache.so -is 16384 -ia 1 -ib 64 -ds 16384 -da 1 -db 64 -- cache2Dcols